#include "dmp/core.h"
#include "dmp/integrity.h"
#include "dmp/stream.h"

#include <stdio.h>
#include <string.h>

#define CHECK(condition) do { \
    if (!(condition)) { \
        (void)fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, #condition); \
        return 1; \
    } \
} while (0)

static const dmp_core_limits limits = { 256U, 1024U, 32U };

/* Independent Main 22.1/22.7 bytes, not generated by the tested encoder. */
static const uint8_t telemetry[] = { 0x45, 0x02, 0xaa, 0xbb };
static const uint8_t stream_l[] = { 0x44, 0x4d, 0x50, 0x04, 0x45, 0x02, 0xaa, 0xbb };
static const uint8_t stream_r[] = {
    0x09, 0x45, 0x02, 0xaa, 0xbb, 0x39, 0xee, 0x4c, 0x1f, 0x00
};

static int test_layers(dmp_stream_mode mode, const uint8_t *wire, size_t size)
{
    uint8_t scratch[272], encoded[272], core[256];
    const dmp_stream_config config = { mode, 256U, 26U };
    dmp_stream_decoder decoder;
    dmp_stream_result received;
    dmp_frame_view view;
    dmp_frame_spec spec;
    dmp_role_policy endpoint = { DMP_ROLE_ENDPOINT, 1U, false };
    size_t written = 0U;
    const uint8_t sync = 0U;

    CHECK(dmp_stream_init(&decoder, config,
                         (dmp_buffer){ scratch, sizeof scratch }, 0U) == DMP_OK);
    if (mode == DMP_STREAM_R) {
        received = dmp_stream_feed(&decoder, (dmp_bytes){ &sync, 1U }, 0U);
        CHECK(received.event == DMP_STREAM_NONE && received.consumed == 1U);
    }
    received = dmp_stream_feed(&decoder, (dmp_bytes){ wire, size }, 1U);
    CHECK(received.status == DMP_OK && received.event == DMP_STREAM_FRAME);
    CHECK(received.consumed == size);
    CHECK(received.frame.size == sizeof telemetry);
    CHECK(memcmp(received.frame.data, telemetry, sizeof telemetry) == 0);
    CHECK(dmp_core_parse(received.frame, &limits, &view).status == DMP_OK);
    CHECK(view.fields.type == DMP_TYPE_TELEM && view.payload.size == 2U);
    CHECK(dmp_core_check_role(&view, &endpoint) == DMP_OK);
    spec.fields = view.fields;
    spec.extensions = view.extensions;
    spec.payload = view.payload;
    spec.trailer = view.trailer;
    CHECK(dmp_core_encode(&spec, &limits, (dmp_buffer){ core, sizeof core },
                          &written) == DMP_OK);
    CHECK(written == sizeof telemetry && memcmp(core, telemetry, written) == 0);
    CHECK(dmp_stream_encode(mode, (dmp_bytes){ core, written },
                            (dmp_buffer){ encoded, sizeof encoded }, &written) == DMP_OK);
    CHECK(written == size && memcmp(encoded, wire, size) == 0);
    return 0;
}

static int test_validation_boundaries(void)
{
    uint8_t with_crc[] = { 0x45, 0x04, 0x10, 0x01, 0xaa, 0xbb, 0xa3, 0xd5, 0x0e, 0xbd };
    const uint8_t malformed_core[] = { 0x45, 0x01, 0xaa };
    uint8_t scratch[272], wire[272];
    const uint8_t sync = 0U;
    dmp_stream_decoder decoder;
    const dmp_stream_config config = { DMP_STREAM_R, 256U, 26U };
    dmp_stream_result received;
    dmp_frame_view view;
    uint32_t crc;
    size_t written;

    CHECK(dmp_core_parse((dmp_bytes){ with_crc, sizeof with_crc }, &limits, &view).status == DMP_OK);
    CHECK(view.trailer.size == 4U);
    CHECK(dmp_crc32c((dmp_bytes){ with_crc, sizeof with_crc - 4U }, &crc) == DMP_OK);
    CHECK(crc == UINT32_C(0xbd0ed5a3));
    with_crc[4] ^= 1U;
    /* Structural success cannot replace an independent integrity decision. */
    CHECK(dmp_core_parse((dmp_bytes){ with_crc, sizeof with_crc }, &limits, &view).status == DMP_OK);
    CHECK(dmp_crc32c((dmp_bytes){ with_crc, sizeof with_crc - 4U }, &crc) == DMP_OK);
    CHECK(crc != UINT32_C(0xbd0ed5a3));

    CHECK(dmp_stream_encode(DMP_STREAM_R,
                            (dmp_bytes){ malformed_core, sizeof malformed_core },
                            (dmp_buffer){ wire, sizeof wire }, &written) == DMP_OK);
    CHECK(dmp_stream_init(&decoder, config,
                         (dmp_buffer){ scratch, sizeof scratch }, 0U) == DMP_OK);
    received = dmp_stream_feed(&decoder, (dmp_bytes){ &sync, 1U }, 0U);
    CHECK(received.event == DMP_STREAM_NONE);
    received = dmp_stream_feed(&decoder, (dmp_bytes){ wire, written }, 1U);
    CHECK(received.event == DMP_STREAM_FRAME);
    CHECK(dmp_core_parse(received.frame, &limits, &view).status != DMP_OK);
    return 0;
}

int main(void)
{
    CHECK(test_layers(DMP_STREAM_L, stream_l, sizeof stream_l) == 0);
    CHECK(test_layers(DMP_STREAM_R, stream_r, sizeof stream_r) == 0);
    CHECK(test_validation_boundaries() == 0);
    return 0;
}
