/* Private P01B provider adapter. Not a public libdmp header: do not install it
 * and do not include Noise, libsodium, or SDK types from include/dmp/.
 *
 * Ownership. The caller owns the provider storage from dmp_provider_size()
 * and every handshake, cipher, and byte buffer. Setup copies the ports and
 * publishes the provider only after startup succeeds. Failure leaves no ready
 * provider, no output length, and wiped caller output. Cleanup erases tracked
 * Noise blocks and registered handshake/cipher objects. Close those objects
 * first; cleanup still erases any that remain.
 *
 * Bounds. scratch_limit is the largest single Noise allocation. retained_limit
 * is the sum of live Noise blocks. Both are capped by the constants below.
 * Encrypt and decrypt do not allocate. Handshake open, split, and DH may.
 *
 * Ports are serialized process-wide, matching the reviewed Noise link-time
 * allocator and entropy hooks. This module does not schedule SEC-1 attempts.
 */
#ifndef DMP_PROVIDER_PORT_H
#define DMP_PROVIDER_PORT_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DMP_PROVIDER_SCRATCH_MAX 16384u
#define DMP_PROVIDER_RETAINED_MAX 131072u
#define DMP_PROVIDER_ROLE_INITIATOR 1
#define DMP_PROVIDER_ROLE_RESPONDER 2

typedef enum dmp_provider_status {
    DMP_PROVIDER_OK = 0,
    DMP_PROVIDER_INVALID = 1,
    DMP_PROVIDER_SETUP_FAILED = 2,
    DMP_PROVIDER_ENTROPY_FAILED = 3,
    DMP_PROVIDER_NO_MEMORY = 4,
    DMP_PROVIDER_REJECTED = 5,
    DMP_PROVIDER_UNSUPPORTED = 6
} dmp_provider_status;

typedef struct dmp_provider_ports {
    /* Nonzero means startup is not eligible. Called from backend init. */
    int (*startup_ready)(void *ctx);
    /* Nonzero means the buffer must not be used. Fill every byte on success. */
    int (*startup_read)(void *ctx, void *bytes, size_t size);
    /* Nonzero means generated bytes must not be used. Fill every byte on success. */
    int (*entropy)(void *ctx, void *bytes, size_t size);
    /* NULL on failure. Return storage aligned for max_align_t. No fallback. */
    void *(*allocate)(void *ctx, size_t size);
    /* Receives a block already erased by the adapter/engine. Must not fail. */
    void (*release)(void *ctx, void *ptr, size_t size);
    void *ctx;
    size_t scratch_limit;
    size_t retained_limit;
} dmp_provider_ports;

typedef struct dmp_provider dmp_provider;

typedef struct dmp_provider_handshake {
    uint64_t words[8];
} dmp_provider_handshake;

typedef struct dmp_provider_cipher {
    uint64_t words[4];
} dmp_provider_cipher;

typedef struct dmp_provider_handshake_keys {
    const uint8_t *local_ephemeral;
    size_t local_ephemeral_len;
    const uint8_t *local_static;
    size_t local_static_len;
    const uint8_t *psk;
    size_t psk_len;
    const uint8_t *prologue;
    size_t prologue_len;
} dmp_provider_handshake_keys;

size_t dmp_provider_size(void);
size_t dmp_provider_block_count(const dmp_provider *provider);
size_t dmp_provider_retained(const dmp_provider *provider);

dmp_provider_status dmp_provider_setup(dmp_provider *provider,
                                      const dmp_provider_ports *ports);
void dmp_provider_cleanup(dmp_provider *provider);

dmp_provider_status dmp_provider_handshake_open(
    dmp_provider *provider, dmp_provider_handshake *handshake,
    const char *protocol_name, int role,
    const dmp_provider_handshake_keys *keys);
dmp_provider_status dmp_provider_handshake_write(
    dmp_provider *provider, dmp_provider_handshake *handshake,
    const uint8_t *payload, size_t payload_len, uint8_t *message,
    size_t message_cap, size_t *message_len);
dmp_provider_status dmp_provider_handshake_read(
    dmp_provider *provider, dmp_provider_handshake *handshake,
    const uint8_t *message, size_t message_len, uint8_t *payload,
    size_t payload_cap, size_t *payload_len);
dmp_provider_status dmp_provider_handshake_hash(
    dmp_provider *provider, const dmp_provider_handshake *handshake,
    uint8_t hash[32]);
dmp_provider_status dmp_provider_handshake_split(
    dmp_provider *provider, dmp_provider_handshake *handshake,
    dmp_provider_cipher *send, dmp_provider_cipher *receive);
dmp_provider_status dmp_provider_handshake_close(
    dmp_provider *provider, dmp_provider_handshake *handshake);

dmp_provider_status dmp_provider_cipher_from_key(
    dmp_provider *provider, dmp_provider_cipher *cipher, const uint8_t *key,
    size_t key_len);
dmp_provider_status dmp_provider_cipher_encrypt(
    dmp_provider *provider, dmp_provider_cipher *cipher, uint64_t packet_number,
    const uint8_t *aad, size_t aad_len, uint8_t *buffer, size_t plaintext_len,
    size_t buffer_cap, size_t *out_len);
dmp_provider_status dmp_provider_cipher_decrypt(
    dmp_provider *provider, dmp_provider_cipher *cipher, uint64_t packet_number,
    const uint8_t *aad, size_t aad_len, uint8_t *buffer, size_t cipher_len,
    size_t buffer_cap, size_t *out_len);
dmp_provider_status dmp_provider_cipher_close(dmp_provider *provider,
                                             dmp_provider_cipher *cipher);

dmp_provider_status dmp_provider_dh_public(dmp_provider *provider,
                                          const uint8_t private_key[32],
                                          uint8_t public_key[32]);
dmp_provider_status dmp_provider_dh_shared(dmp_provider *provider,
                                          const uint8_t private_key[32],
                                          const uint8_t public_key[32],
                                          uint8_t shared[32]);

#ifdef __cplusplus
}
#endif

#endif
